version: '3'
services:
  app:
    image: "srome/d4d-hate-speech-detector:latest"
    networks:
      - web_nw
    ports:
      - "80:8000"
  nginx:
    image: "srome/d4d-hate-speech-detector:nginx"
    networks:
      - web_nw
networks:
  web_nw:
    driver: bridge